Fetch the BART station list
The Station class encapsulates the fetching/parsing of BART's station API. Upon
application startup, all stations are fetched and their names displayed in a
list.

Lessons:
* Parsing XML in Java is no fun
* The INTERNET permission is required in the manifest. Leaving it out throws
  SocketException: Permission denied